import * as express from 'express';
import {preMenuTime,preMenu, preList, liveList, liveDetail} from './betsService';
import * as auth from './authService';
export const router= express.Router();
router.get("/bets/pre/menu/:hours",preMenuTime);
router.get("/bets/pre/menu",preMenu);
router.get("/bets/pre/list",preList);
router.get("/bets/live/list",liveList);
router.get("/bets/live/detail/:id",liveDetail);
router.post('/accounts/login',auth.login);